### ISSUE TITLE
kontakdaten?

### ISSUE THREAD

**Issue by foobar32** [cutterkom/generativeart#10]
Moin!
Auf deiner Seite gibt es leider kein Impressum (https://www.bmjv.de/DE/Verbraucherportal/DigitalesTelekommunikation/Impressumspflicht/Impressumspflicht_node.html) was es leider schwierig macht, mit dir in Kontakt zu treten.
EIGENTLICH wollte ich nur wissen, ob destatiscleanr noch weiterentwickelt wird, da trotz der destatis-API die Daten in SEHR unaufgeräumter Form zur Verfügung gestellt werden.

**Comment by cutterkom** [comment]
hey!
Du hast recht, das ist irgendwann mal aus Versehen rausgefallen. Ich nehm's wieder mit rein. 

Zu deiner Frage: Ich habe seit einiger Zeit nicht mehr mit Destatis-CSV-Daten gearbeitet. Deshalb kann ich gar nicht genau sagen, inwieweit es Veränderungen gab und wo man das package anpassen müsste. Hast du ein Beispiel?

**Comment by cutterkom** [comment]
Ist deine Anfrage noch aktuell?
