### ISSUE TITLE
Error: Failed to install 'generativeart' from GitHub:

### ISSUE THREAD

**Issue by awiden91** [cutterkom/generativeart#11]
Hello,

I am trying to install this package but getting some errors. Please let me know what I should do to successfully install the package. Thank you for your assistance! 
![image](https://user-images.githubusercontent.com/30248269/111084275-9e19da80-84df-11eb-8d49-8a984d85783c.png)

**Comment by cutterkom** [comment]
Try again by running `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")` before installing the package.

**Comment by awiden91** [comment]
That worked! I appreciate the help.

**Comment by SandeepNarasimhan** [comment]
@cutterkom thank you
