### ISSUE TITLE
background color?

### ISSUE THREAD

**Issue by JWellsBio** [cutterkom/generativeart#4]
I've tried several tricks and can't seem to change background color. Suggestions?

**Comment by cutterkom** [comment]
Hey! Sorry, I was not aware of the issue. 

What you can do is to fork the repo and/or change the `generate_plot()` function ( https://github.com/cutterkom/generativeart/blob/master/R/generate_plot.R) by adding a `theme()` component

```
ggplot(aes(...)) + 
... + 
theme(panel.background = element_rect(fill = "hotpink"),
            plot.background = element_rect(fill = "hotpink"))
```

Does it work?

**Comment by JWellsBio** [comment]
Sorry for the late reply. Thanks for getting back. Error was entirely on my part. No issue. Thanks for your help!!

**Comment by cutterkom** [comment]
No worries! Meanwhile there was a pull request and background color is now a function parameter.
