### ISSUE TITLE
I'm not install 

### ISSUE THREAD

**Issue by jbarriosmuriel** [cutterkom/generativeart#6]
Hi

I can't install the repositorie. I have installed the packages `ggplot2`, `magrittr`, `purrr` and `dplyr`. Then execute devtools::install_github("cutterkom/generativeart") and the next error is printed by terminal.

Installing package into ‘C:/Users/.../Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'generativeart' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (convertido del aviso) package 'magrittr' was built under R version 3.6.3
Ejecución interrumpida
ERROR: lazy loading failed for package 'generativeart'
* removing 'C:/Users/FRIKIS/Documents/R/win-library/3.6/generativeart'
Error: Failed to install 'generativeart' from GitHub:
  (converted from warning) installation of package 

Thanks for your response

**Comment by cutterkom** [comment]
Hey!
Do you use the R version 3.6.3? If yes, you should upgrade to at least R 3.4.1, which is needed for the package to work correctly

**Comment by vfodder** [comment]
Hey there,

Great work, itching to road test but I've just tried to install but I'm getting this warning message.

package ‘/Users/davegerold/Documents/GENERATIVE ART/Generative Package/generativeart-master/generativeart.Rproj’ is not available (for R version 4.0.2) 
> 

Do you know when an update for the latest version of R will be available?

Thanks in advance!

**Comment by cutterkom** [comment]
Hey! I am a bit confused by your error message, because an `.Rproj` file is an R-project file, but not a package itself.

Did you install the package with `devtools::install_github("cutterkom/generativeart")`?
